<a href="https://colab.research.google.com/github/Kyash24/Python_Concepts_In_Action/blob/main/06_HANDS_ON_NUMPY_%26_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HANDS ON PANDAS

Que 1 - Create the list, tuplem ,set with elements from 1 to 10
      - Create a list of indexes ["a","b",......"j"] and map with the elements
      - Convert each of these pandas series

In [ ]:
my_list=[1,2,3,4,5,6,7,8,9,10]
my_tup=(1,2,3,4,5,6,7,8,9,10)
my_set={1,2,3,4,5,6,7,8,9,10}
print(type(my_list))
print(type(my_tup))
print(type(my_set))

<class 'list'>
<class 'tuple'>
<class 'set'>

In [ ]:
import numpy as mp
import pandas as pd

In [ ]:
my_index = ["a","b","c","d","e","f","g","h","i","j"]
series_from_list = pd.Series(data=my_list, index=my_index)
series_from_tuple = pd.Series(data=my_tup, index=my_index)
series_from_set = pd.Series(data=list(my_set), index=my_index)
print(series_from_list)
print(series_from_tuple)
print(series_from_set)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64
a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64
a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

Que 2- Create a simple series with 10 numbers. -- Print the first 5 elem. --  Print the last 5 elements. --Update the 5th index with value of 500. -- Delete the first element.

In [ ]:
sample_series = pd.Series([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(sample_series)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
sample_series.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
sample_series.tail()

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
sample_series[5]=500
print(sample_series)

0      1
1      2
2      3
3      4
4      5
5    500
6      7
7      8
8      9
9     10
dtype: int64

In [ ]:
p1 = sample_series.drop(0,inplace=True)
print(p1)

None

Que 3 - Create a nested list and a dictionary(store thevalues in the form of a List. --Convert atleast 3 keys. -- Convert these into pandas DataFrame

In [ ]:
import pandas as pd

# Create a nested list
nested_list = [
    ['Apple', 10, 1.50],
    ['Banana', 20, 0.75],
    ['Cherry', 15, 2.00],
    ['Date', 25, 1.20]
]

# Convert nested list to DataFrame
df_from_list = pd.DataFrame(nested_list, columns=['Fruit', 'Quantity', 'Price'])
print("DataFrame from nested list:")
display(df_from_list)

DataFrame from nested list:

    Fruit  Quantity  Price
0   Apple        10   1.50
1  Banana        20   0.75
2  Cherry        15   2.00
3    Date        25   1.20

In [ ]:
# Create a dictionary with list values (at least 3 keys)
my_dict = {
    'City': ['New York', 'Los Angeles', 'Chicago'],
    'Population': [8419000, 3980000, 2705000],
    'State': ['NY', 'CA', 'IL'],
    'Area_sq_mi': [302.6, 468.7, 234.0]
}

# Convert dictionary to DataFrame
df_from_dict = pd.DataFrame(my_dict)
print("\nDataFrame from dictionary:")
display(df_from_dict)

DataFrame from dictionary:

          City  Population State  Area_sq_mi
0     New York     8419000    NY       302.6
1  Los Angeles     3980000    CA       468.7
2      Chicago     2705000    IL       234.0

In [ ]:
# Rename the column name from "Car-model"  to " Model"

In [ ]:
df_from_dict.rename(columns = {"City":"Model"}, inplace=True)

In [ ]:
df_from_dict

         Model  Population State  Area_sq_mi
0     New York     8419000    NY       302.6
1  Los Angeles     3980000    CA       468.7
2      Chicago     2705000    IL       234.0

In [ ]:
# Select all the records  where population is greater than 3000000
# Select all the records where the model is Chicago and population is greater than 2500000
# Select the records where the model is New York or population is greater than 3900000

In [ ]:
df_from_dict.loc[df_from_dict["Population"]>3000000]

         Model  Population State  Area_sq_mi
0     New York     8419000    NY       302.6
1  Los Angeles     3980000    CA       468.7

In [ ]:
df_from_dict.loc[(df_from_dict["Model"] == "Chicago") & (df_from_dict["Population"] > 2500000)]

     Model  Population State  Area_sq_mi
2  Chicago     2705000    IL       234.0

In [ ]:
# Select the records where the model is New York or population is greater than 3900000
df_from_dict.loc[(df_from_dict["Model"] == "New York") | (df_from_dict["Population"] > 3900000)]

         Model  Population State  Area_sq_mi
0     New York     8419000    NY       302.6
1  Los Angeles     3980000    CA       468.7